CREATE TABLE DEMOGIT.CLIENT (
        NUMCLI DECIMAL(5, 0) NOT NULL DEFAULT 0 ,
        NOMCLI CHAR(30) CCSID 1147 NOT NULL DEFAULT '' ,
        PRECLI CHAR(30) CCSID 1147 NOT NULL DEFAULT '' ,
        TELCLI DECIMAL(10, 0) NOT NULL DEFAULT 0 )
        RCDFMT CLIENTF;
